---

# Modeled on: https://github.com/geerlingguy/mac-dev-playbook/blob/master/default.config.yml

# Not yet installed

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - chromedriver
  - doxygen
  - gettext
  - gifsicle
  - git
  - go
  - gpg
  - hub
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  #- nvm
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  # my stuff starts from here
  - rmate
  - erlang
  - shellcheck
  - watchman
  - maxima
  - mariadb
  - redis
  - ruby-build
  - tmux
  - wget
  - git
  - vtop
  - htop
  - reattach-to-user-namespace
  - mpd
  - lua
  - ffmpeg
  - terminal-notifier
  - the_silver_searcher
  - tree 
  - lynx
  - awscli
  - imagemagick
  - mongo
  - phantomjs
  - gpg
  - dockutil
  

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/php

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  # - fing # Download link keeps getting changed, d'oh!
  - firefox
  - google-chrome
  - handbrake
  - licecap
  - limechat
  - macvim
  - nvalt
  - sequel-pro
  - skitch
  - slack
  - sublime-text
  - transmit
  - vagrant
  - virtualbox
  # my stuff starts from here
  - alfred
  - vlc
  - google-chrome
  - chrome-devtools
  - chromium
  - firefox
  - vivaldi
  - brave
  - opera
  - skype
  - slack
  - telegram
  - atom
  - sublime-text
  - textmate
  - rmate
  - macvim
  - electron
  - yarn
  - keypad-layout
  - xquartz
  - gitter
  - fantastical
  - acorn
  - enpass
  - keybase
  - franz
  - marp
  - chatology
  - docker
  - transmit
  - iterm2
  - Caskroom/cask/electron
  - hyper
  - hammerspoon
  
# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages: #[]
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
  - tmuxinator
  - bundler
  - lunchy
  - launchy
  
npm_packages: #[]
  # - name: webpack
  #   state: present # present/absent/latest, default: present
  #   version: "^2.6" # default: N/A
  - bozon
  - electron
  - electron-positioner
  - electron-devtools-installer
  - electron-cli
  - electron-forge
  - electron-packager
  - react-native-cli
  - electron-prebuilt
  - 
    
pip_packages: []
  # - name: mkdocs
  #   state: present # present/absent/latest, default: present
  #   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

dockitems_to_remove:
  - Contacts
  - Notes
  - FaceTime
  - iTunes
  - iBooks
  - App Store
  - Calendar
 
dockitems_to_persist:
  - name: Google Chrome
    path: "/Applications/Google Chrome.app"
    pos: 1
  - name: Firefox
    path: "/Applications/Firefox.app"
    pos: 2
  - name: TextMate
    path: /Applications/TextMate.app
    pos: 3
  - name: Slack
    path: /Applications/Slack.app
    pos: 4
  - name: VirtualBox
    path: /Applications/VirtualBox.app
    pos: 5
  - name: Terminal
    path: /Applications/Utilities/Terminal.app
    pos: 6
  - name: iTerm
    path: /Applications/Utilities/iTerm.app
    pos: 7
  - name: Enpass
    path: /Applications/Enpass.app
    pos: 7
  - name: Skype
    path: /Applications/Skype.app
    pos: 8
