--- 
  - name: install_rvm_gpg
    shell: "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3"
    
  - name: install_rvm_curl  
    shell: \curl -sSL https://get.rvm.io | bash -s stable --ruby
    